### ISSUE TITLE
My Repo Access

### ISSUE THREAD

**Issue by Aurora0001** [Dog2puppy/dog-bot#1]
Hi, you seem to have added me to a contributor to this repo. Did you intend to do this, or was it a mistake, since I've not heard of your project or talked to you about it, and I wouldn't want to keep repo access if I'm not supposed to have it.

If you're able to clear this up, I'd really appreciate it.

**Comment by Dog2puppy** [comment]
@Aurora0001 Aren't you the bot used for GitBook?

**Comment by Aurora0001** [comment]
Nope, I'm not a bot (as you might have guessed) but I did make a GitBook for my bot [here](https://aurora0001.gitbooks.io/learnprogrammingbot/content/index.html). Perhaps that's what confused you?

**Comment by Dog2puppy** [comment]
@Aurora0001 Okay, I understand. I will remove your Contributer Status (unless if you do want to help).

**Comment by Aurora0001** [comment]
I think I've found out what was causing GitHub to think I contributed: it had linked `anonymous@gitbook.io` to my account, so it assumed that I must have committed to your repo too.

I don't have any experience with Discord so I can't help, unfortunately. Good luck with your project anyway.
